In [45]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

### 1. Dataset Loading: (Marks 2) • Load the dataset into a Pandas DataFrame 
• Display the first 10 rows

In [82]:
dataset = pd.read_csv("HousePricePrediction.csv")
dataset.sample(10)

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
426,426,80,RL,12800,Inside,1Fam,5,1989,1989,Wd Sdng,0.0,1518.0,275000.0
2417,2417,20,RL,8540,Corner,1Fam,8,1956,2003,VinylSd,691.0,925.0,NaN
2711,2711,60,RL,11025,Inside,1Fam,5,1992,1993,HdBoard,0.0,1334.0,NaN
2692,2692,20,RL,11024,Corner,1Fam,5,2005,2006,VinylSd,0.0,1400.0,NaN
921,921,90,RL,8777,Inside,Duplex,7,1900,2003,MetalSd,0.0,1272.0,145900.0
1251,1251,120,RL,3136,Corner,TwnhsE,5,2003,2003,VinylSd,0.0,1405.0,171750.0
1196,1196,60,RL,14054,Inside,1Fam,5,2006,2006,VinylSd,0.0,879.0,219210.0
1216,1216,90,RM,8930,Inside,Duplex,5,1978,1978,VinylSd,0.0,0.0,112000.0
352,352,50,RL,9084,Inside,1Fam,6,1941,1950,VinylSd,380.0,616.0,95000.0
1624,1624,20,RL,13008,Inside,1Fam,5,1956,1956,MetalSd,0.0,882.0,NaN

### 2. Data Exploration: (Marks 2) • Display the shape of the dataset  
• Check data types of all columns  
• Generate summary statistics of numerical features

In [83]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 2919 entries, 0 to 2918
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            2919 non-null   int64
 1   MSSubClass    2919 non-null   int64
 2   MSZoning      2915 non-null   str
 3   LotArea       2919 non-null   int64
 4   LotConfig     2919 non-null   str
 5   BldgType      2919 non-null   str
 6   OverallCond   2919 non-null   int64
 7   YearBuilt     2919 non-null   int64
 8   YearRemodAdd  2919 non-null   int64
 9   Exterior1st   2918 non-null   str
 10  BsmtFinSF2    2918 non-null   float64
 11  TotalBsmtSF   2918 non-null   float64
 12  SalePrice     1460 non-null   float64
dtypes: float64(3), int64(6), str(4)
memory usage: 296.6 KB

In [84]:
dataset.describe()

,Id,MSSubClass,LotArea,OverallCond,YearBuilt,YearRemodAdd,BsmtFinSF2,TotalBsmtSF,SalePrice
count,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2918.000000,2918.000000,1460.000000
mean,1459.000000,57.137718,10168.114080,5.564577,1971.312778,1984.264474,49.582248,1051.777587,180921.195890
std,842.787043,42.517628,7886.996359,1.113131,30.291442,20.894344,169.205611,440.766258,79442.502883
min,0.000000,20.000000,1300.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,34900.000000
25%,729.500000,20.000000,7478.000000,5.000000,1953.500000,1965.000000,0.000000,793.000000,129975.000000
50%,1459.000000,50.000000,9453.000000,5.000000,1973.000000,1993.000000,0.000000,989.500000,163000.000000
75%,2188.500000,70.000000,11570.000000,6.000000,2001.000000,2004.000000,0.000000,1302.000000,214000.000000
max,2918.000000,190.000000,215245.000000,9.000000,2010.000000,2010.000000,1526.000000,6110.000000,755000.000000

### 3. Data Cleaning: (Marks 2) • Identify missing values  
• Handle missing values appropriately  
• Check and remove duplicate records if any

In [85]:
dataset.isna().sum()

Id                 0
MSSubClass         0
MSZoning           4
LotArea            0
LotConfig          0
BldgType           0
OverallCond        0
YearBuilt          0
YearRemodAdd       0
Exterior1st        1
BsmtFinSF2         1
TotalBsmtSF        1
SalePrice       1459
dtype: int64

In [86]:
dataset[['MSZoning', 'Exterior1st']] = dataset[['MSZoning', 'Exterior1st']].apply(lambda x: x.fillna(x.mode()[0]))

In [87]:
dataset[['TotalBsmtSF','BsmtFinSF2']] = dataset[['TotalBsmtSF','BsmtFinSF2']].fillna(dataset[['TotalBsmtSF','BsmtFinSF2']].median())

In [88]:
dataset.drop(columns=['SalePrice'], inplace=True)

In [89]:
dataset.isna().sum()

Id              0
MSSubClass      0
MSZoning        0
LotArea         0
LotConfig       0
BldgType        0
OverallCond     0
YearBuilt       0
YearRemodAdd    0
Exterior1st     0
BsmtFinSF2      0
TotalBsmtSF     0
dtype: int64

In [90]:
dataset.duplicated().sum()

np.int64(0)

In [91]:
dataset[dataset.duplicated()]

Empty DataFrame
Columns: [Id, MSSubClass, MSZoning, LotArea, LotConfig, BldgType, OverallCond, YearBuilt, YearRemodAdd, Exterior1st, BsmtFinSF2, TotalBsmtSF]
Index: []

### 4. Feature Selection: (Marks 2) • Identify relevant features for analysis  
• Remove unnecessary columns such as identifiers (e.g., Id)

In [92]:
dataset.drop(columns=['Id'], inplace=True)

In [93]:
dataset.value_counts()

MSSubClass  MSZoning  LotArea  LotConfig  BldgType  OverallCond  YearBuilt  YearRemodAdd  Exterior1st  BsmtFinSF2  TotalBsmtSF
120         RM        4435     Inside     TwnhsE    5            2003       2003          VinylSd      0.0         848.0          5
                      4426     Inside     TwnhsE    5            2004       2004          VinylSd      0.0         848.0          4
90          RL        7018     Inside     Duplex    5            1979       1979          HdBoard      0.0         0.0            3
160         FV        2117     Inside     Twnhs     5            2000       2000          MetalSd      0.0         756.0          3
            RM        2522     Inside     Twnhs     5            2004       2004          VinylSd      0.0         970.0          3
                                                                                                                                 ..
                      1936     Inside     Twnhs     7            1970       1970          CemntBd      0.0         546.0          1
                      1894     Inside     TwnhsE    5            1970       1970          CemntBd      0.0         546.0          1
20          RL        20000    Inside     1Fam      7            1960       1996          VinylSd      0.0         1224.0         1
85          RL        10441    Inside     1Fam      5            1992       1992          HdBoard      0.0         912.0          1
60          RL        9627     Inside     1Fam      5            1993       1994          HdBoard      0.0         996.0          1
Name: count, Length: 2879, dtype: int64

### 5. Data Preprocessing: (Marks 2) • Convert categorical variables into numerical form (encoding)  
• Preparing the dataset for machine learning and display it’s preview in the output

In [94]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 2919 entries, 0 to 2918
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   MSSubClass    2919 non-null   int64
 1   MSZoning      2919 non-null   str
 2   LotArea       2919 non-null   int64
 3   LotConfig     2919 non-null   str
 4   BldgType      2919 non-null   str
 5   OverallCond   2919 non-null   int64
 6   YearBuilt     2919 non-null   int64
 7   YearRemodAdd  2919 non-null   int64
 8   Exterior1st   2919 non-null   str
 9   BsmtFinSF2    2919 non-null   float64
 10  TotalBsmtSF   2919 non-null   float64
dtypes: float64(2), int64(5), str(4)
memory usage: 251.0 KB

In [95]:
cols_to_encode = ['MSZoning', 'LotConfig', 'BldgType', 'Exterior1st']


if cols_to_encode[0] in dataset.columns:
    dataset = pd.get_dummies(dataset, columns=cols_to_encode, dtype='float64')
    print("Encoding successful!")
else:
    print("Columns already encoded or missing.")

dataset.head()

Encoding successful!

,MSSubClass,LotArea,OverallCond,YearBuilt,YearRemodAdd,BsmtFinSF2,TotalBsmtSF,MSZoning_C (all),MSZoning_FV,MSZoning_RH,...,Exterior1st_CemntBd,Exterior1st_HdBoard,Exterior1st_ImStucc,Exterior1st_MetalSd,Exterior1st_Plywood,Exterior1st_Stone,Exterior1st_Stucco,Exterior1st_VinylSd,Exterior1st_Wd Sdng,Exterior1st_WdShing
0,60,8450,5,2003,2003,0.0,856.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,20,9600,8,1976,1976,0.0,1262.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,60,11250,5,2001,2002,0.0,920.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,70,9550,5,1915,1970,0.0,756.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,60,14260,5,2000,2000,0.0,1145.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [96]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 2919 entries, 0 to 2918
Data columns (total 37 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   MSSubClass           2919 non-null   int64
 1   LotArea              2919 non-null   int64
 2   OverallCond          2919 non-null   int64
 3   YearBuilt            2919 non-null   int64
 4   YearRemodAdd         2919 non-null   int64
 5   BsmtFinSF2           2919 non-null   float64
 6   TotalBsmtSF          2919 non-null   float64
 7   MSZoning_C (all)     2919 non-null   float64
 8   MSZoning_FV          2919 non-null   float64
 9   MSZoning_RH          2919 non-null   float64
 10  MSZoning_RL          2919 non-null   float64
 11  MSZoning_RM          2919 non-null   float64
 12  LotConfig_Corner     2919 non-null   float64
 13  LotConfig_CulDSac    2919 non-null   float64
 14  LotConfig_FR2        2919 non-null   float64
 15  LotConfig_FR3        2919 non-null   float64
 16  LotConfig_Inside     2919 non-null   float64
 17  BldgType_1Fam        2919 non-null   float64
 18  BldgType_2fmCon      2919 non-null   float64
 19  BldgType_Duplex      2919 non-null   float64
 20  BldgType_Twnhs       2919 non-null   float64
 21  BldgType_TwnhsE      2919 non-null   float64
 22  Exterior1st_AsbShng  2919 non-null   float64
 23  Exterior1st_AsphShn  2919 non-null   float64
 24  Exterior1st_BrkComm  2919 non-null   float64
 25  Exterior1st_BrkFace  2919 non-null   float64
 26  Exterior1st_CBlock   2919 non-null   float64
 27  Exterior1st_CemntBd  2919 non-null   float64
 28  Exterior1st_HdBoard  2919 non-null   float64
 29  Exterior1st_ImStucc  2919 non-null   float64
 30  Exterior1st_MetalSd  2919 non-null   float64
 31  Exterior1st_Plywood  2919 non-null   float64
 32  Exterior1st_Stone    2919 non-null   float64
 33  Exterior1st_Stucco   2919 non-null   float64
 34  Exterior1st_VinylSd  2919 non-null   float64
 35  Exterior1st_Wd Sdng  2919 non-null   float64
 36  Exterior1st_WdShing  2919 non-null   float64
dtypes: float64(32), int64(5)
memory usage: 843.9 KB