In [19]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

### 1. Dataset Loading: (Marks 2) • Load the dataset into a Pandas DataFrame 
• Display the first 10 rows

In [20]:
dataset = pd.read_csv("HousePricePrediction.csv")
dataset.sample(10)

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
2830,2830,20,RL,7488,Inside,1Fam,5,2005,2005,VinylSd,0.0,1208.0,NaN
712,712,120,RL,4671,Inside,TwnhsE,5,1988,1989,HdBoard,0.0,1228.0,189000.0
432,432,160,RM,1920,Inside,TwnhsE,5,1971,1971,HdBoard,0.0,765.0,122500.0
37,37,20,RL,8532,Inside,1Fam,6,1954,1990,Wd Sdng,0.0,1297.0,153000.0
1930,1930,85,RL,7669,Inside,1Fam,6,1992,1993,HdBoard,110.0,828.0,NaN
2087,2087,70,RM,4800,Inside,1Fam,5,1910,2003,AsbShng,0.0,680.0,NaN
1262,1262,50,RL,11250,Inside,1Fam,5,1957,1989,Wd Sdng,0.0,1104.0,161500.0
1827,1827,50,RM,6120,Inside,1Fam,6,1938,1950,Wd Sdng,0.0,952.0,NaN
1583,1583,60,RL,9375,Inside,1Fam,5,1997,1997,VinylSd,0.0,1040.0,NaN
998,998,30,RM,9786,Inside,1Fam,4,1922,1950,Wd Sdng,0.0,1007.0,91000.0

### 2. Data Exploration: (Marks 2) • Display the shape of the dataset  
• Check data types of all columns  
• Generate summary statistics of numerical features

In [21]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 2919 entries, 0 to 2918
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            2919 non-null   int64
 1   MSSubClass    2919 non-null   int64
 2   MSZoning      2915 non-null   str
 3   LotArea       2919 non-null   int64
 4   LotConfig     2919 non-null   str
 5   BldgType      2919 non-null   str
 6   OverallCond   2919 non-null   int64
 7   YearBuilt     2919 non-null   int64
 8   YearRemodAdd  2919 non-null   int64
 9   Exterior1st   2918 non-null   str
 10  BsmtFinSF2    2918 non-null   float64
 11  TotalBsmtSF   2918 non-null   float64
 12  SalePrice     1460 non-null   float64
dtypes: float64(3), int64(6), str(4)
memory usage: 296.6 KB

In [22]:
dataset.describe()

,Id,MSSubClass,LotArea,OverallCond,YearBuilt,YearRemodAdd,BsmtFinSF2,TotalBsmtSF,SalePrice
count,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2918.000000,2918.000000,1460.000000
mean,1459.000000,57.137718,10168.114080,5.564577,1971.312778,1984.264474,49.582248,1051.777587,180921.195890
std,842.787043,42.517628,7886.996359,1.113131,30.291442,20.894344,169.205611,440.766258,79442.502883
min,0.000000,20.000000,1300.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,34900.000000
25%,729.500000,20.000000,7478.000000,5.000000,1953.500000,1965.000000,0.000000,793.000000,129975.000000
50%,1459.000000,50.000000,9453.000000,5.000000,1973.000000,1993.000000,0.000000,989.500000,163000.000000
75%,2188.500000,70.000000,11570.000000,6.000000,2001.000000,2004.000000,0.000000,1302.000000,214000.000000
max,2918.000000,190.000000,215245.000000,9.000000,2010.000000,2010.000000,1526.000000,6110.000000,755000.000000

### 3. Data Cleaning: (Marks 2) • Identify missing values  
• Handle missing values appropriately  
• Check and remove duplicate records if any

In [23]:
dataset.isna().sum()

Id                 0
MSSubClass         0
MSZoning           4
LotArea            0
LotConfig          0
BldgType           0
OverallCond        0
YearBuilt          0
YearRemodAdd       0
Exterior1st        1
BsmtFinSF2         1
TotalBsmtSF        1
SalePrice       1459
dtype: int64

In [24]:
dataset[['MSZoning', 'Exterior1st']] = dataset[['MSZoning', 'Exterior1st']].apply(lambda x: x.fillna(x.mode()[0]))

In [25]:
dataset[['TotalBsmtSF','BsmtFinSF2']] = dataset[['TotalBsmtSF','BsmtFinSF2']].fillna(dataset[['TotalBsmtSF','BsmtFinSF2']].median())

In [26]:
# dataset.drop(columns=['SalePrice'], inplace=True)

In [27]:
dataset.isna().sum()

Id                 0
MSSubClass         0
MSZoning           0
LotArea            0
LotConfig          0
BldgType           0
OverallCond        0
YearBuilt          0
YearRemodAdd       0
Exterior1st        0
BsmtFinSF2         0
TotalBsmtSF        0
SalePrice       1459
dtype: int64

In [28]:
dataset.duplicated().sum()

np.int64(0)

In [29]:
dataset[dataset.duplicated()]

Empty DataFrame
Columns: [Id, MSSubClass, MSZoning, LotArea, LotConfig, BldgType, OverallCond, YearBuilt, YearRemodAdd, Exterior1st, BsmtFinSF2, TotalBsmtSF, SalePrice]
Index: []

### 4. Feature Selection: (Marks 2) • Identify relevant features for analysis  
• Remove unnecessary columns such as identifiers (e.g., Id)

In [30]:
dataset.drop(columns=['Id'], inplace=True)

In [31]:
dataset.value_counts()

MSSubClass  MSZoning  LotArea  LotConfig  BldgType  OverallCond  YearBuilt  YearRemodAdd  Exterior1st  BsmtFinSF2  TotalBsmtSF  SalePrice
60          RL        8450     Inside     1Fam      5            2003       2003          VinylSd      0.0         856.0        208500.0     1
20          RL        9600     FR2        1Fam      8            1976       1976          MetalSd      0.0         1262.0       181500.0     1
60          RL        11250    Inside     1Fam      5            2001       2002          VinylSd      0.0         920.0        223500.0     1
70          RL        9550     Corner     1Fam      5            1915       1970          Wd Sdng      0.0         756.0        140000.0     1
60          RL        14260    FR2        1Fam      5            2000       2000          VinylSd      0.0         1145.0       250000.0     1
                                                                                                                                            ..
                      7917     Inside     1Fam      5            1999       2000          VinylSd      0.0         953.0        175000.0     1
20          RL        13175    Inside     1Fam      6            1978       1988          Plywood      163.0       1542.0       210000.0     1
70          RL        9042     Inside     1Fam      9            1941       2006          CemntBd      0.0         1152.0       266500.0     1
20          RL        9717     Inside     1Fam      6            1950       1996          MetalSd      1029.0      1078.0       142125.0     1
                      9937     Inside     1Fam      6            1965       1965          HdBoard      290.0       1256.0       147500.0     1
Name: count, Length: 1460, dtype: int64

### 5. Data Preprocessing: (Marks 2) • Convert categorical variables into numerical form (encoding)  
• Preparing the dataset for machine learning and display it’s preview in the output

In [32]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 2919 entries, 0 to 2918
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   MSSubClass    2919 non-null   int64
 1   MSZoning      2919 non-null   str
 2   LotArea       2919 non-null   int64
 3   LotConfig     2919 non-null   str
 4   BldgType      2919 non-null   str
 5   OverallCond   2919 non-null   int64
 6   YearBuilt     2919 non-null   int64
 7   YearRemodAdd  2919 non-null   int64
 8   Exterior1st   2919 non-null   str
 9   BsmtFinSF2    2919 non-null   float64
 10  TotalBsmtSF   2919 non-null   float64
 11  SalePrice     1460 non-null   float64
dtypes: float64(3), int64(5), str(4)
memory usage: 273.8 KB

In [33]:
cols_to_encode = ['MSZoning', 'LotConfig', 'BldgType', 'Exterior1st']


if cols_to_encode[0] in dataset.columns:
    dataset = pd.get_dummies(dataset, columns=cols_to_encode, dtype='float64')
    print("Encoding successful!")
else:
    print("Columns already encoded or missing.")

dataset.head()

Encoding successful!

,MSSubClass,LotArea,OverallCond,YearBuilt,YearRemodAdd,BsmtFinSF2,TotalBsmtSF,SalePrice,MSZoning_C (all),MSZoning_FV,...,Exterior1st_CemntBd,Exterior1st_HdBoard,Exterior1st_ImStucc,Exterior1st_MetalSd,Exterior1st_Plywood,Exterior1st_Stone,Exterior1st_Stucco,Exterior1st_VinylSd,Exterior1st_Wd Sdng,Exterior1st_WdShing
0,60,8450,5,2003,2003,0.0,856.0,208500.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,20,9600,8,1976,1976,0.0,1262.0,181500.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,60,11250,5,2001,2002,0.0,920.0,223500.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,70,9550,5,1915,1970,0.0,756.0,140000.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,60,14260,5,2000,2000,0.0,1145.0,250000.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [34]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 2919 entries, 0 to 2918
Data columns (total 38 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   MSSubClass           2919 non-null   int64
 1   LotArea              2919 non-null   int64
 2   OverallCond          2919 non-null   int64
 3   YearBuilt            2919 non-null   int64
 4   YearRemodAdd         2919 non-null   int64
 5   BsmtFinSF2           2919 non-null   float64
 6   TotalBsmtSF          2919 non-null   float64
 7   SalePrice            1460 non-null   float64
 8   MSZoning_C (all)     2919 non-null   float64
 9   MSZoning_FV          2919 non-null   float64
 10  MSZoning_RH          2919 non-null   float64
 11  MSZoning_RL          2919 non-null   float64
 12  MSZoning_RM          2919 non-null   float64
 13  LotConfig_Corner     2919 non-null   float64
 14  LotConfig_CulDSac    2919 non-null   float64
 15  LotConfig_FR2        2919 non-null   float64
 16  LotConfig_FR3        2919 non-null   float64
 17  LotConfig_Inside     2919 non-null   float64
 18  BldgType_1Fam        2919 non-null   float64
 19  BldgType_2fmCon      2919 non-null   float64
 20  BldgType_Duplex      2919 non-null   float64
 21  BldgType_Twnhs       2919 non-null   float64
 22  BldgType_TwnhsE      2919 non-null   float64
 23  Exterior1st_AsbShng  2919 non-null   float64
 24  Exterior1st_AsphShn  2919 non-null   float64
 25  Exterior1st_BrkComm  2919 non-null   float64
 26  Exterior1st_BrkFace  2919 non-null   float64
 27  Exterior1st_CBlock   2919 non-null   float64
 28  Exterior1st_CemntBd  2919 non-null   float64
 29  Exterior1st_HdBoard  2919 non-null   float64
 30  Exterior1st_ImStucc  2919 non-null   float64
 31  Exterior1st_MetalSd  2919 non-null   float64
 32  Exterior1st_Plywood  2919 non-null   float64
 33  Exterior1st_Stone    2919 non-null   float64
 34  Exterior1st_Stucco   2919 non-null   float64
 35  Exterior1st_VinylSd  2919 non-null   float64
 36  Exterior1st_Wd Sdng  2919 non-null   float64
 37  Exterior1st_WdShing  2919 non-null   float64
dtypes: float64(33), int64(5)
memory usage: 866.7 KB

### Save the cleaned dataset for model prediction

In [35]:
dataset.to_csv("House_Price_Cleaned_Dataset.csv", index=False)